sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"
before_script:
  - npm install async
  - npm install -g if-node-version
script:
  - "if-node-version '>=4' npm test"
  - "npm run test@2"
after_success:
  - npm run codecov
