sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_script:
  - npm install async
  - npm install -g if-node-version
script:
  - "if if-node-version '>=4'; then npm test; else npm run test@2; fi"
after_success:
  - npm run codecov
