sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

env:
  - ESLINT_VERSION=3.1
  - ESLINT_VERSION=3
  - ESLINT_VERSION=4

cache:
  directories:
    - node_modules

before_script:
  - npm i --no-save async
  - npm i --no-save eslint@$ESLINT_VERSION; true

script:
  - if [ $ESLINT_VERSION = 4 ]; then npm test; else nyc npm run -s test:_mocha; fi

after_success:
  - npm run codecov
