os:
  - linux
  - osx
  - windows

language: node_js
node_js:
  - "8.10.0"
  - "10"
  - "12"

# env:
#   - ESLINT_VERSION=5
#   - ESLINT_VERSION=6

# matrix:
#   exclude:
#     # Reduce build jobs.
#     - os: osx
#       env: ESLINT_VERSION=6
#     - os: windows
#       env: ESLINT_VERSION=6

before_script:
  - npm i --no-save async
  # - if [ $ESLINT_VERSION = "5" ]; then npm i --no-save eslint@^5.0.0; else true; fi

script:
  # - if [ $ESLINT_VERSION = "5" ]; then npm run -s lint; else true; fi
  - npm run -s lint
  - npm test

after_success:
  - npm run codecov
