sudo: false

os:
  - linux
  - osx
  - windows

language: node_js
node_js:
  - "8.10.0"
  - "10"
  - "12"

env:
  - ESLINT_VERSION=4
  - ESLINT_VERSION=5

matrix:
  exclude:
    # Reduce build jobs.
    - os: osx
      env: ESLINT_VERSION=4
    - os: windows
      env: ESLINT_VERSION=4

before_script:
  - npm i --no-save async
  - npm i --no-save eslint@$ESLINT_VERSION; true

script:
  - if [ $ESLINT_VERSION = "5" ]; then npm run lint; else true; fi
  - npm test

after_success:
  - npm run codecov
